[package]
name = "kairo-object"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
kairo-core = { path = "../kairo-core" }
kairo-statement = { path = "../kairo-statement" }
serde = { version = "1", features = ["derive"] }
toml = "0.8"

[lib]
name = "kairo_object"
path = "src/lib.rs"

[lints]
workspace = true
