[package]
name = "kairo-keystore"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
base64 = "=0.21.7"
fs2 = "0.4"
kairo-core = { path = "../kairo-core" }
kairo-identity = { path = "../kairo-identity" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
tempfile = "3"

[lib]
name = "kairo_keystore"
path = "src/lib.rs"

[lints]
workspace = true
