[package]
name = "kairo-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
base64 = "=0.21.7"
clap = { version = "4.4", features = ["derive", "env"] }
http-body-util = "0.1"
hyper = { version = "1", features = ["client", "http1"] }
hyper-util = { version = "0.1", features = ["client", "client-legacy", "http1", "tokio"] }
kairo-bundle = { path = "../kairo-bundle" }
kairo-core = { path = "../kairo-core" }
kairo-daemon = { path = "../kairo-daemon" }
kairo-daemon-client = { path = "../kairo-daemon-client" }
kairo-git = { path = "../kairo-git" }
kairo-identity = { path = "../kairo-identity" }
kairo-keystore = { path = "../kairo-keystore" }
kairo-object = { path = "../kairo-object" }
kairo-statement = { path = "../kairo-statement" }
kairo-store = { path = "../kairo-store" }
kairo-web = { path = "../kairo-web" }
nix = { version = "0.29", default-features = false, features = ["signal"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time", "fs"] }

[dev-dependencies]
ed25519-dalek = "=2.1.1"
kairo-test-support = { path = "../kairo-test-support" }
tempfile = "3"

[[bin]]
name = "kairo"
path = "src/main.rs"

[lints]
workspace = true
