[package]
name = "kairo-statement"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
base64 = "=0.21.7"
kairo-identity = { path = "../kairo-identity" }
kairo-core = { path = "../kairo-core" }
semver = "1"
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
ed25519-dalek = "=2.1.1"
serde_json = "1"

[lib]
name = "kairo_statement"
path = "src/lib.rs"

[lints]
workspace = true
