#!/usr/bin/env bash
#
# Seed a fresh `~/.kairo`-style store with the same shape the
# inspector's MSW mock registry uses, so the SPA can be walked
# end-to-end against a real daemon (`kairo web start`).
#
# Mirrors `frontend/packages/api-client/src/mock/registry.ts`:
#
#   - **Alice** — primary actor; signs Alpha + Beta. Her
#                 `/actors/<alice>` Signed-statements panel is
#                 the audit-table happy path: 3 revisions, 2
#                 branches, 2 tags, 1 capability grant — every
#                 envelope-signing kind the v1 daemon exposes.
#                 (`ObjectGenesis` is excluded server-side from
#                 the per-actor index by design.)
#   - **Bob**   — secondary actor; subject of one capability
#                 grant from Alice and trusts Alice. His
#                 Signed-statements panel renders just the
#                 trust-grant envelope.
#   - **Carol** — third actor; blocks Alice (untrusted opinion).
#                 Her Signed-statements panel renders just the
#                 trust-block envelope.
#   - **Alpha** — rich object: 3 revisions (linear), 2 branches
#                 (head + experimental), 2 tags (v1.0.0,
#                 v1.1.0), one capability grant.
#   - **Beta**  — genesis-only object; exercises every empty-
#                 state panel.
#
# Revisions use fake `git:sha256:…` ids (no real Git repo). The
# verifier reports `indeterminate` against these (no commit to
# check the manifest binding against), which matches what the
# Alpha mock fixture's verify-object panel renders.
#
# Usage:
#   scripts/smoke-seed.sh [STORE_DIR]
#
# `STORE_DIR` defaults to `$(mktemp -d)/kairo-store`. The
# script prints the path + canonical IDs at the end. Set
# `KAIRO=/path/to/kairo` to point at a non-default binary.

set -euo pipefail

STORE_DIR="${1:-$(mktemp -d)/kairo-store}"
mkdir -p "$STORE_DIR"
export KAIRO_STORE="$STORE_DIR"

KAIRO="${KAIRO:-./target/release/kairo}"
if [[ ! -x "$KAIRO" ]]; then
    echo "error: kairo binary not found at $KAIRO" >&2
    echo "       run \`cargo build --bin kairo --release\` first," >&2
    echo "       or set \$KAIRO to override the path." >&2
    exit 1
fi

# Manifest the revisions all bind to. The MVP store accepts any
# valid manifest; the inspector doesn't read it back.
MANIFEST="$(mktemp)"
cat >"$MANIFEST" <<'EOF'
[kairo]
schema = 1
kind = "software"
name = "smoke-fixture"
summary = "Generated by scripts/smoke-seed.sh — see top of script."

[content]
kind = "tree"
EOF
trap 'rm -f "$MANIFEST"' EXIT

# Helper: extract `<key> = <value>` from CLI output.
extract() {
    local key="$1"
    grep -oE "^${key} = [A-Za-z0-9]+" | head -1 | awk '{print $3}'
}

echo "==> seeding store at $STORE_DIR"
echo

# ---------------------------------------------------------------------------
# Actors

echo "  creating alice…"
ALICE=$("$KAIRO" actor create --kind person --generate-attestation-key 2>/dev/null | extract actor)

echo "  creating bob…"
BOB=$("$KAIRO" actor create --kind person --generate-attestation-key 2>/dev/null | extract actor)

echo "  creating carol…"
CAROL=$("$KAIRO" actor create --kind person --generate-attestation-key 2>/dev/null | extract actor)

# ---------------------------------------------------------------------------
# Object: Alpha (rich)

echo "  creating alpha…"
ALPHA=$("$KAIRO" object create --actor "$ALICE" --kind software 2>/dev/null | extract object)

echo "  signing alpha revisions r1, r2 (parent r1), r3 (parent r2)…"
ALPHA_R1=$("$KAIRO" revision create \
    --actor "$ALICE" \
    --object "$ALPHA" \
    --revision "git:sha256:0000000000000000000000000000000000000000000000000000000000000001" \
    --manifest "$MANIFEST" \
    2>/dev/null | extract statement)

ALPHA_R2=$("$KAIRO" revision create \
    --actor "$ALICE" \
    --object "$ALPHA" \
    --revision "git:sha256:0000000000000000000000000000000000000000000000000000000000000002" \
    --parent "git:sha256:0000000000000000000000000000000000000000000000000000000000000001" \
    --manifest "$MANIFEST" \
    2>/dev/null | extract statement)

ALPHA_R3=$("$KAIRO" revision create \
    --actor "$ALICE" \
    --object "$ALPHA" \
    --revision "git:sha256:0000000000000000000000000000000000000000000000000000000000000003" \
    --parent "git:sha256:0000000000000000000000000000000000000000000000000000000000000002" \
    --manifest "$MANIFEST" \
    2>/dev/null | extract statement)

echo "  setting branches: head → r3 (alice), experimental → r2 (alice)…"
"$KAIRO" branch set --actor "$ALICE" --object "$ALPHA" --revision "$ALPHA_R3" >/dev/null 2>&1
"$KAIRO" branch set --actor "$ALICE" --object "$ALPHA" --revision "$ALPHA_R2" --name experimental >/dev/null 2>&1

echo "  binding tags: v1.0.0 → r2, v1.1.0 → r3 (both by alice)…"
"$KAIRO" tag bind --actor "$ALICE" --object "$ALPHA" --version 1.0.0 --revision "$ALPHA_R2" >/dev/null 2>&1
"$KAIRO" tag bind --actor "$ALICE" --object "$ALPHA" --version 1.1.0 --revision "$ALPHA_R3" >/dev/null 2>&1

echo "  granting alice → bob ObjectVersionTag on alpha…"
"$KAIRO" capability grant \
    --grantor "$ALICE" \
    --grantee "$BOB" \
    --object "$ALPHA" \
    --kind ObjectVersionTag >/dev/null 2>&1

# ---------------------------------------------------------------------------
# Object: Beta (genesis only)

echo "  creating beta (genesis only)…"
BETA=$("$KAIRO" object create --actor "$ALICE" --kind software 2>/dev/null | extract object)

# ---------------------------------------------------------------------------
# Trust opinions about Alice

echo "  bob trusts alice; carol blocks alice…"
"$KAIRO" trust grant --by "$BOB" --of "$ALICE" --reason "smoke-seed: bob trusts alice" >/dev/null 2>&1
"$KAIRO" trust block --by "$CAROL" --of "$ALICE" --reason "smoke-seed: carol blocks alice" >/dev/null 2>&1

# ---------------------------------------------------------------------------
# Summary

cat <<EOF

==> seeded.

store        $STORE_DIR
manifest     $MANIFEST (cleaned up on exit)

actors                                            (signed envelopes)
  alice      $ALICE   3 rev / 2 branch / 2 tag / 1 grant
  bob        $BOB                                       1 trust grant
  carol      $CAROL                                     1 trust block

objects
  alpha      $ALPHA      (3 revs / 2 branches / 2 tags / 1 grant)
  beta       $BETA       (genesis only)

revisions (alpha)
  r1         $ALPHA_R1
  r2         $ALPHA_R2
  r3         $ALPHA_R3

next:
  KAIRO_STORE=$STORE_DIR $KAIRO daemon start
  KAIRO_STORE=$STORE_DIR $KAIRO web start --spa-dir frontend/apps/web-client/dist

inspector URLs (drop into your browser at http://127.0.0.1:<web-port>/):
  /                           dashboard
  /objects/${ALPHA#kairo:object:}     rich object — every populated panel
  /objects/${BETA#kairo:object:}      genesis-only — every empty-state panel
  /actors/${ALICE#kairo:actor:}       full signed-statements audit table
  /actors/${BOB#kairo:actor:}         single trust grant
  /actors/${CAROL#kairo:actor:}       single trust block
  /statements/${ALPHA_R3#kairo:stmt:}   alpha r3 envelope (typed summary)
EOF
